name: Pull Request Check
on:
  pull_request:
    branches:
      - trunk
      - 'branch-*'
  check_run:
    types: [created, rerequested, requested_action]

jobs:
  testing:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        python-version: [2.7]
        java: [8]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        name: Deploy JDK ${{ matrix.java }}
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: x64
      - uses: actions/setup-python@v2
        name: Deploy python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Base checks (ambari-server and ambari-agent modules dependencies)
        run: |
          mvn clean test -am -pl ambari-server,ambari-agent